version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/mvc-framework
      - ./build/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: build/docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: ${CURRENT_USER_ID}
    volumes:
      - .:/var/www/mvc-framework/
    networks:
      - default
    hostname: "mvc-framework-local"
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

  postgres:
    image: postgres:14.8-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: books